package my.noveldokusha.coreui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance

@Composable
fun ColorScheme.isLightTheme() = background.luminance() > 0.5

val light_colorScheme = ColorScheme(
    primary = HighlightLight,
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD6E4FF),
    onPrimaryContainer = HighlightLight,
    inversePrimary = HighlightLight,
    secondary = HighlightLight,
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE6A817).copy(alpha = 0.15f),
    onSecondaryContainer = Color(0xFFC68A00),
    tertiary = Success600,
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Success50,
    onTertiaryContainer = Success900,
    background = BgLight,
    onBackground = TextLight,
    surface = BgLight,
    onSurface = TextLight,
    surfaceVariant = BgLight,
    onSurfaceVariant = SubTextLight,
    surfaceTint = HighlightLight,
    inverseSurface = TextLight,
    inverseOnSurface = BgLight,
    error = Color(0xFFE53935),
    onError = Color(0xFFFFFFFF),
    errorContainer = Error200,
    onErrorContainer = Error900,
    outline = StrokeLight,
    outlineVariant = StrokeLight,
    scrim = Color.Black.copy(alpha = 0.5f),
    surfaceBright = SubBgLight,
    surfaceDim = Grey100,
    surfaceContainerLowest = Grey0,
    surfaceContainerLow = BgLight,
    surfaceContainer = SubBgLight,
    surfaceContainerHigh = PopupLight,
    surfaceContainerHighest = Grey100,
)

val dark_colorScheme = ColorScheme(
    primary = HighlightDark,
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF003A7A),
    onPrimaryContainer = HighlightDark,
    inversePrimary = HighlightDark,
    secondary = HighlightDark,
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE6A817).copy(alpha = 0.15f),
    onSecondaryContainer = Color(0xFFC68A00),
    tertiary = Color(0xFF4CAF50),
    onTertiary = Color(0xFF003910),
    tertiaryContainer = Success800,
    onTertiaryContainer = Success50,
    background = BgDark,
    onBackground = TextDark,
    surface = BgDark,
    onSurface = TextDark,
    surfaceVariant = BgDark,
    onSurfaceVariant = SubTextDark,
    surfaceTint = HighlightDark,
    inverseSurface = TextDark,
    inverseOnSurface = BgDark,
    error = Color(0xFFCF6679),
    onError = Color(0xFF690005),
    errorContainer = Error800,
    onErrorContainer = Error50,
    outline = StrokeDark,
    outlineVariant = StrokeDark,
    scrim = Color.Black.copy(alpha = 0.5f),
    surfaceBright = Grey700,
    surfaceDim = BgDark,
    surfaceContainerLowest = Grey1000,
    surfaceContainerLow = BgDark,
    surfaceContainer = SubBgDark,
    surfaceContainerHigh = PopupDark,
    surfaceContainerHighest = Grey600,
)

val black_colorScheme = ColorScheme(
    primary = HighlightDark,
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF003A7A),
    onPrimaryContainer = HighlightDark,
    inversePrimary = HighlightDark,
    secondary = HighlightDark,
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE6A817).copy(alpha = 0.15f),
    onSecondaryContainer = Color(0xFFC68A00),
    tertiary = Color(0xFF4CAF50),
    onTertiary = Color(0xFF003910),
    tertiaryContainer = Success800,
    onTertiaryContainer = Success50,
    background = BgBlack,
    onBackground = TextDark,
    surface = BgBlack,
    onSurface = TextDark,
    surfaceVariant = BgBlack,
    onSurfaceVariant = SubTextDark,
    surfaceTint = HighlightDark,
    inverseSurface = TextDark,
    inverseOnSurface = BgBlack,
    error = Color(0xFFCF6679),
    onError = Color(0xFF690005),
    errorContainer = Error800,
    onErrorContainer = Error50,
    outline = StrokeBlack,
    outlineVariant = StrokeBlack,
    scrim = Color.Black.copy(alpha = 0.5f),
    surfaceBright = Grey800,
    surfaceDim = BgBlack,
    surfaceContainerLowest = Grey1000,
    surfaceContainerLow = BgBlack,
    surfaceContainer = SubBgBlack,
    surfaceContainerHigh = PopupBlack,
    surfaceContainerHighest = Grey700,
)