package my.noveldokusha.coreui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.luminance

@Composable
fun ColorScheme.isLightTheme() = background.luminance() > 0.5

val light_colorScheme = ColorScheme(
    primary = HighlightLight,
    onPrimary = SubBgLight,
    primaryContainer = HighlightLight.copy(alpha = 0.1f),
    onPrimaryContainer = HighlightLight,
    inversePrimary = HighlightLight,
    secondary = HighlightLight,
    onSecondary = SubBgLight,
    secondaryContainer = HighlightLight,
    onSecondaryContainer = SubBgLight,
    tertiary = Grey200,
    onTertiary = Grey600,
    tertiaryContainer = Grey50,
    onTertiaryContainer = Grey900,
    background = BgLight,
    onBackground = TextLight,
    surface = SubBgLight,
    onSurface = TextLight,
    surfaceVariant = SubBgLight,
    onSurfaceVariant = TextLight,
    surfaceTint = HighlightLight,
    inverseSurface = TextLight,
    inverseOnSurface = BgLight,
    error = Error300,
    onError = Grey900,
    errorContainer = Error200,
    onErrorContainer = Grey800,
    outline = StrokeLight,
    outlineVariant = StrokeLight,
    scrim = Grey300,
    surfaceBright = SubBgLight,
    surfaceDim = Grey100,
    surfaceContainerLowest = Grey0,
    surfaceContainerLow = BgLight,
    surfaceContainer = SubBgLight,
    surfaceContainerHigh = Grey75,
    surfaceContainerHighest = Grey100,
)

val dark_colorScheme = ColorScheme(
    primary = HighlightDark,
    onPrimary = TextDark,
    primaryContainer = HighlightDark.copy(alpha = 0.1f),
    onPrimaryContainer = HighlightDark,
    inversePrimary = HighlightDark,
    secondary = HighlightDark,
    onSecondary = TextDark,
    secondaryContainer = HighlightDark,
    onSecondaryContainer = SubBgDark,
    tertiary = Grey700,
    onTertiary = Grey300,
    tertiaryContainer = Grey600,
    onTertiaryContainer = Grey50,
    background = BgDark,
    onBackground = TextDark,
    surface = SubBgDark,
    onSurface = TextDark,
    surfaceVariant = SubBgDark,
    onSurfaceVariant = TextDark,
    surfaceTint = HighlightDark,
    inverseSurface = TextDark,
    inverseOnSurface = BgDark,
    error = Error600,
    onError = Grey25,
    errorContainer = Error800,
    onErrorContainer = Grey50,
    outline = StrokeDark,
    outlineVariant = StrokeDark,
    scrim = Grey800,
    surfaceBright = Grey700,
    surfaceDim = BgDark,
    surfaceContainerLowest = Grey1000,
    surfaceContainerLow = BgDark,
    surfaceContainer = SubBgDark,
    surfaceContainerHigh = Grey700,
    surfaceContainerHighest = Grey600,
)

val black_colorScheme = ColorScheme(
    primary = HighlightDark,
    onPrimary = TextDark,
    primaryContainer = HighlightDark.copy(alpha = 0.1f),
    onPrimaryContainer = HighlightDark,
    inversePrimary = HighlightDark,
    secondary = HighlightDark,
    onSecondary = TextDark,
    secondaryContainer = HighlightDark,
    onSecondaryContainer = SubBgBlack,
    tertiary = Grey800,
    onTertiary = Grey300,
    tertiaryContainer = Grey700,
    onTertiaryContainer = Grey50,
    background = BgBlack,
    onBackground = TextDark,
    surface = SubBgBlack,
    onSurface = TextDark,
    surfaceVariant = SubBgBlack,
    onSurfaceVariant = TextDark,
    surfaceTint = HighlightDark,
    inverseSurface = TextDark,
    inverseOnSurface = BgBlack,
    error = Error600,
    onError = Grey25,
    errorContainer = Error800,
    onErrorContainer = Grey50,
    outline = StrokeBlack,
    outlineVariant = StrokeBlack,
    scrim = Grey900,
    surfaceBright = Grey800,
    surfaceDim = BgBlack,
    surfaceContainerLowest = Grey1000,
    surfaceContainerLow = BgBlack,
    surfaceContainer = SubBgBlack,
    surfaceContainerHigh = Grey800,
    surfaceContainerHighest = Grey700,
)