name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  buildDebug:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Set up JDK environment
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle version to 8.13
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.13

      - name: Build debug APK
        run: |
          gradle assembleDebug

      - name: Upload debug APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/**/*.apk
